version: "3"

services:
  react-app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    # volumes:
    #  - ./src:/app/src:ro
    environment:
      - REACT_APP_NAME=cyoung kim
      - REACT_APP_TITLE=kiwi
    env_file:
      - ./.env
    networks:
      - taptalk-network

networks:
  taptalk-network:
